# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 01:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0002_auto_20170929_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
